services:
  - type: web
    name: organigramme-req
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --timeout 600 --graceful-timeout 30 app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: AUTO_SYNC_ENABLED
        value: "1"
